# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
contact_us:
   url: /contact_us
   param: { module: contact_us, action: index }

contact_approv:
   url: /contact_approv
   param: { module: contact_us, action: emailApprov }

# registration rules
registration:
  url: /registration
  param: { module: registration, action: index }

registration_proceed:
  url: /registration_proceed
  param: { module: registration, action: registrationProceed }

registration_activate:
  url: /registration/activate/:code
  param: { module: registration, action: activate }



# guard rules
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
